apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
spec:
  description: project description
  sourceRepos: 
    - "*"
  destinations:
    - namespace: ns1
      server: https://kubernetes.default.svc
      
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceBlacklist:
    - group: ""
      kind: NetworkPolicy
