apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
spec:
  description: application in this project will only create namespace, and only do deployment in a namespace.
  sourceRepos: 
    - "*"
  destinations:
    - namespace: ns1
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: Deployment
