apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds-https
  namespace: argocd
  labels:
    # credential template specific
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  # password goes here, NOTE: dont push secrets into git, use sealed secrets as a solution for secrets in gitops.
  type: git
  url: https://github.com/MedievalMarkup
  password: "add github token"
  username: MedievalMarkup