apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: auto-sync-app
  namespace: argocd
spec:
  destination:
    namespace: auto-sync-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: sub-dir-argo
    repoURL: "https://github.com/MedievalMarkup/Manifests-ArgoCD.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - CreateNamespace=true