apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    #--------------path in git repo -------------------
    path: helm/webapp
    #----------------manifests repo-----------------------
    repoURL: "https://github.com/MedievalMarkup/argocd-webapp-config.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true