apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: replace-resources
  namespace: argocd
spec:
  destination:
    namespace: replace-resources
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: sync-options/replace
    repoURL: "https://github.com/MedievalMarkup/Manifests-ArgoCD.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      # on application level, all manifests under the application will get replaced.
      - Replace=true